### ISSUE TITLE
请问android该如何保存网络资源图片

### ISSUE THREAD

**Issue by yuanbolin** [react-native-community/react-native-cameraroll#117] opened 2019-12-13 07:27 UTC
# Question

**Comment by thekevinbrown** [comment] 2020-01-30 23:53
Images that are not on the phone, accessible by network, are not currently loaded by this library. There's another issue (#72) we're tracking for this functionality.

**Comment by bartolkaruza** [comment] 2020-06-01 09:29
closing as duplicate of #72 (I guess :))

**Closed by bartolkaruza** 2020-06-01 09:29 UTC
