### ISSUE TITLE
Unify and draft common standard of Photos PHAsset URL (ph://) to communicate with other framework

### ISSUE THREAD

**Issue by dreampiggy** [react-native-community/react-native-cameraroll#111] opened 2019-11-20 04:18 UTC
See related issue: https://github.com/DylanVann/react-native-fast-image/issues/314#issuecomment-555827640

react-native-cameraroll now hard-coded to construct the PHAsset URL, with the following format:

```
ph://F2A9F582-BA45-4308-924E-6D146B784A09/L0/001
```

However, [SDWebImage](https://github.com/SDWebImage/SDWebImagePhotosPlugin) 's photo plugin, construct the PHAsset URL, with the following format:

```
photos://asset/F2A9F582-BA45-4308-924E-6D146B784A09/L0/001
```

Which cause the in-compatible isssues.

For user, who want to use this library to query Photos Library images, and then display on that [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image), who use SDWebImage's loading system, will fail to just use the URL. They have to do a URL-rewrite to match these different compatible issues.

I saw that the URL is hard-coded to generated here : 

https://github.com/react-native-community/react-native-cameraroll/blob/03bc028efe2bf4b603feb25ba3943ec1760f7fe0/ios/RNCCameraRollManager.m#L258

Any reason, or common standard to communicate betweeen different library, to communicate the `PHAsset local identifier` this thing, via URL ?

**Comment by dreampiggy** [comment] 2019-11-20 04:23
One issue about this `ph://F2A9F582-BA45-4308-924E-6D146B784A09/L0/001`

This is not standard URL format, see [URL RFC 1738](https://tools.ietf.org/html/rfc1738). Because it does not have the `host` component. Which is inlivad to use in `NSURL` this object of iOS.

**Comment by bartolkaruza** [comment] 2019-11-29 20:26
Thanks for opening this discussion. I would love to move towards some standard as I feel there are too many interoperability issues caused by this url format. I'm unfamiliar with everyone's preferences on this subject, so I'm happy to follow your lead on this @dreampiggy . If anything needs to change for Cameraroll, a PR is also more than welcome.
Is there any particular perspective from FB @JoshuaGross ?

**Comment by dreampiggy** [comment] 2019-11-30 02:22
SDWebImagePhotosPlugin already change to use the ph:// format in new versions...

I think to avoid future other libraries whi use Photos Framework , a common standard way to generate the URL is preferred.

**Comment by jwmLLL** [comment] 2019-12-07 07:29
i use sdwebImage in rn Image can not display , how can i change ph://  path

**Comment by bartolkaruza** [comment] 2020-05-26 10:42
Closing this for now as `SDWebImage`, `react-native-fast-image` and `react-native-cameraroll` are aligned on the `ph://` uri.

**Closed by bartolkaruza** 2020-05-26 10:42 UTC
