### ISSUE TITLE
How to save remote videos in iOS 

### ISSUE THREAD

**Issue by abdulbasit1248** [react-native-community/react-native-cameraroll#51] opened 2019-04-30 12:27 UTC
As this package only working for saving remote pictures in iOS but in case to save remote videos to iPhone, app crashes or get stuck.For this problem the solution is implemented with demo video url's.
You have to write native code in swift for iOS case and then communicate between Native and JS which is very simple and implemented as .#50

**Comment by bartolkaruza** [comment] 2019-06-13 06:17
duplicate of #49

**Closed by bartolkaruza** 2019-06-13 06:17 UTC
