### ISSUE TITLE
node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.h:10: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-native-community/react-native-cameraroll#95] opened 2019-10-11 22:05 UTC
# Bug

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 28.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.60.5
```

Library version:1.2.1

## Steps To Reproduce

1. npm i @react-native-community/cameraroll --save
1. Add RNCCameraroll.xcodeproj to Libraries
1. Add libRNCCameraroll.a to Build Phases -> Link Binary With Library
1. Run app

Describe what you expected to happen:

1. Should not fail

**Comment by fangxndoit** [comment] 2019-10-18 02:18
same Q！ i want to die

**Comment by bartolkaruza** [comment] 2019-11-07 13:39
You shouldn't manually add the to libraries on React Native 0.60 + . Did you try just `npm i ...` and then running `cd ios && pod install`, followed by running the app?

**Comment by fairlycasual** [comment] 2019-11-14 18:11
Currently in the process of upgrading from RN 0.59.10 to 0.61.4, and keep encountering the same issue. I have not attempted to manually link the library. All of the related errors I get are: 
```❌  /Users/devsstupidmac/campanion/node_modules/@react-native-community/cameraroll/ios/RNCAssetsLibraryRequestHandler.h:8:9: 'React/RCTBridge.h' file not found

#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~



❌  /Users/devsstupidmac/campanion/node_modules/@react-native-community/cameraroll/ios/RNCAssetsLibraryRequestHandler.h:8:9: 'React/RCTBridge.h' file not found

#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~



❌  /Users/devsstupidmac/campanion/node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.h:10:9: 'React/RCTBridgeModule.h' file not found

#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~



❌  /Users/devsstupidmac/campanion/node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.h:10:9: 'React/RCTBridgeModule.h' file not found

#import <React/RCTBridgeModule.h>
```

I have tried to alter the #import syntax to #import "React/RCTBridgeModule.h" to no avail. Any updates on this issue?

**Comment by bartolkaruza** [comment] 2019-11-19 10:00
@fairlycasual I assume you did not get to your problematic state the same way OP did? The original issue is caused by an incomplete upgrade from manual linking <0.60 and cocoapods >0.60.
Unless you can give me a clean `react-native init` repro that shows this issue, I don't have any way of helping you.

My first thought though, is that something didn't go quite right in your upgrade process. Try comparing your current project state to a clean init project and look for the differences in project.pbxproj (other than the id's).

**Comment by fairlycasual** [comment] 2019-11-19 15:45
Thanks for the reply @bartolkaruza, I appreciate your time and that you took a look at it from my somewhat ambiguous stack trace. I solved this issue shortly after asking. When I get back to a good stopping point to checkout my previous commit, I can provide an update on those changes if it'll provide value.

**Comment by ddr2108** [comment] 2019-12-06 22:10
@fairlycasual what was your solution - I'm running into a similar issue with `'RCTAssetsLibraryRequestHandler.h' file not found`

**Comment by dcenatiempo** [comment] 2019-12-31 20:12
Same issue here. I'm on RN 60.5, just trying to install @react-native-community/cameraroll. At first I ignored the install instructions which said to manually link. After that didn't work, I tried manually linking. Either way I can't seem to properly install this package. Help!!!

**Comment by JacobTBralish** [comment] 2020-01-12 23:22
Same issue on RN 60.4. Did the manual install and cannot get xcode to build because of this issue. Haven't been able to get it to work at all.

**Comment by JulioDuram** [comment] 2020-01-22 01:46
> @fairlycasual what was your solution - I'm running into a similar issue with `'RCTAssetsLibraryRequestHandler.h' file not found`

Try this: https://github.com/react-native-community/react-native-cameraroll

The React Native Community package worked for me instead of the original react-native-camereroll

**Comment by yaoyongmin** [comment] 2020-02-21 00:17
devDependencies": {
    "@react-native-community/cameraroll": "^1.4.1",

**Comment by bartolkaruza** [comment] 2020-05-21 08:08
Closing this as it seems to be a magnet for unrelated issues. The library appears to link automatically correctly on a clean project. Issues like the one above are related to project specific settings. If you feel that I'm missing something that's wrong specifically with @react-native-community/cameraroll please make a new issue and provide me with a minimal repro so we can investigate.

**Closed by bartolkaruza** 2020-05-21 08:08 UTC
Labels: question

**Comment by ForestFairy666** [comment] 2023-05-11 08:39
few problems in the picture saving process:
1. Currently the code saves the image in the Recent folder,
we said we'll create a folder (if does't exist) to all the ECGs from the app and save them there
2. BUG: Currently when uploading a video I can see that two identical pictures are saved, why? which one are we taking? can we delete the other one?

**Comment by ForestFairy666** [comment] 2023-05-11 08:41
<img width="406" alt="image" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/83014156/62cbd366-307e-4b2e-8cb2-84541a76e5af">
look at the bamba image. it apears twice for no reason at the recent photos and not a dedicated album
