### ISSUE TITLE
Issue in fetching the last saved file on iOS cameraRoll 

### ISSUE THREAD

**Issue by dev2612** [react-native-community/react-native-cameraroll#82] opened 2019-09-06 10:16 UTC
# Question

I am facing a problem with videos specifically. 

Scenario: I have to save a file on cameraRoll and pick the last saved file from the camera roll to share it further.

iOS cameraRoll retains the video's original metadata and thus save the file with createdate and not with today's Date.

So when I pick the last saved file, I get someother file instead of the video I just saved to cameraRoll

The getPhotos function works well with Android when I pick the last saved file it returns the correct file. 

On iOS the problem is the file saved on camera roll is saved with video file’s create date. 

Any help in this regards will be highly appreciable. it is bit Urgent. Thanks in advance.

**Comment by bartolkaruza** [comment] 2019-11-07 14:54
Why not use the resolved URI after saving instead of fetching the first photo?

Please note that you might have an issue with the URI, related to this: https://github.com/react-native-community/react-native-cameraroll/issues/52

I'm closing this issue for now, as I think this is a user question and not a bug. Let me know if you would like me to reopen as a bug, with a description of what exactly isn't working as expected.

**Closed by bartolkaruza** 2019-11-07 14:54 UTC
