### ISSUE TITLE
Cant save video file  (PHPhotosErrorDomain error -1.)

### ISSUE THREAD

**Issue by MehmetDT** [react-native-community/react-native-cameraroll#196] opened 2020-06-10 13:56 UTC
# Question
Helloı i trying save .mp4 file from instagram my gallery. Android working fine but ios have some problem . Its giving me Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.) error. Can anybody help me please ?

**Comment by bartolkaruza** [comment] 2020-06-16 09:17
duplicate of #186

**Closed by bartolkaruza** 2020-06-16 09:17 UTC
