### ISSUE TITLE
Not able to download an image from URL iOS

### ISSUE THREAD

**Issue by Nextt1** [react-native-community/react-native-cameraroll#160] opened 2020-03-28 14:36 UTC
I'm trying to download an image from the URL using the following code but getting an error.

    CameraRoll.saveToCameraRoll(data.image)
            .then(Alert.alert('Success', 'Photo added to camera roll!'));

Error: 

    [Error: The operation couldn’t be completed. (Cocoa error -1.)]

I did an automatic installation of the library since I'm using 0.61.5 version of react-native and I'm using 1.5.2 version of cameraRoll library.

**Comment by roshan-p** [comment] 2020-04-07 03:39
Did you find any solutions ?

**Comment by taschik** [comment] 2020-04-14 17:20
I think, it's the same issue like this: https://github.com/react-native-community/react-native-cameraroll/issues/157

**Comment by abdulbasit1248** [comment] 2020-04-15 12:37
Same issue with react native version +60

**Comment by huyhai** [comment] 2020-04-25 05:46
same here

**Comment by kufufu9** [comment] 2020-04-30 01:29
These caused by https://github.com/react-native-community/react-native-cameraroll/pull/134

**Comment by bartolkaruza** [comment] 2020-05-07 18:53
closing as duplicate of #157

**Closed by bartolkaruza** 2020-05-07 18:53 UTC

**Comment by bartolkaruza** [comment] 2020-05-07 19:02
Does anyone have time to help and make a PR with a fix for this issue? There appears to be a solution at #159 (comment) . I'm happy to review and merge a well tested PR. Cheers
