### ISSUE TITLE
iOS - returned uri cannot be used for upload image to server

### ISSUE THREAD

**Issue by LuongTruong** [react-native-community/react-native-cameraroll#52] opened 2019-05-02 06:50 UTC
Bug details
========

I am using the returned `uri` from CameraRoll as a path to upload image to server, but the image cannot be upload. Below is an example of image `uri`

    ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001

To Reproduce
==========

[RN Fetch Blob](https://github.com/joltup/rn-fetch-blob) is used for making upload request.

    RNFetchBlob.fetch("PUT", url, { <== url: is the path to our server
        'Content-Type': contentType,
    }, RNFetchBlob.wrap(path))   <== path: is the uri from CameraRoll: "ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001"

        .uploadProgress((written, total) => {

            progress(written, total);
        })
        .then((res) => {

            if (R.path(["respInfo", "status"], res) === StatusCode.HTTP_200) {

                success(res);

            } else {

                fail(res);
            }
        })
        .catch((error) => {

            fail(error);
        })

This code is runnable with the Default CameraRoll in React native 0.57.4. After the library is moved to GitHub and change to use PHAsset, this code run fail. There is only one different thing that is the `uri` return from CameraRoll

Expected Behavior
==============

I am able to upload the image to server using the link `ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001`

Question:
=======

From what I know, the link `ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001` is from PHAsset of iOS. I wonder if it is really available to be used to upload image to server.

I the link is original unavailable for uploading image to server, then please let me know what should I do to convert that link.

Environment:
==========

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
      Memory: 36.78 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Thank you guys for helping me!

**Comment by truongluong1314520** [comment] 2019-05-02 09:12
Hi guys, I found a way to convert the PHAsset link to use able link:

[Convert PHAsset to assets-library](https://github.com/ivpusic/react-native-image-crop-picker/issues/384#issuecomment-317628146)

I don't know if this is the correct way. Please feel free to close this issue if it is.

**Comment by assaqqaf** [comment] 2019-05-07 06:35
I have the same issue, however, the suggested solution to convert PHAsset to assets-library is not stable.

Any other solution to this problem?

**Comment by JoshuaGross** [comment] 2019-05-20 16:58
How does upload fail exactly? Does it throw some exception, or upload the wrong thing? #58 may resolve this issue but I'm not entirely sure what problem you're having just from the description here.

**Comment by pisacode** [comment] 2019-06-21 10:48
Here is a litte code turn uri to old format

```
const appleId = x.uri.substring(5, 41);
const ext = 'MOV';
var videoUri = `assets-library://asset/asset.${ext}?id=${appleId}&ext=${ext}`;
```

**Comment by manithin** [comment] 2019-06-29 08:28
facing the same issue. The image also cannot be viewed in the image components using uri. The image data from node looks like this:

image:{
height: 682
isStored: true
playableDuration: 0
uri: "ph://509F4C50-7A98-4503-BC1A-1753D1559BC4/L0/001"
width: 909
}

**Comment by manithin** [comment] 2019-06-29 13:13
> How does upload fail exactly? Does it throw some exception, or upload the wrong thing? #58 may resolve this issue but I'm not entirely sure what problem you're having just from the description here.

@JoshuaGross passed the uri to RNFetchBlob and it fails. the error: "No such file 'ph://AF32193E-88E0-44BD-BC1C-EA9920940D61/L0/001'"

**Comment by ramazanarslan** [comment] 2019-07-19 22:08
I have converted to `assets-library`, it is worked for me. 
this is example

``` pathRaw='ph://99D53A1F-FEEF-40E1-8BB3-7DD55A43C8B7/L0/001';

var regex = /:\/\/(.{36})\//i;
var result = pathRaw.match(regex);
console.log("result", "assets-library://asset/asset.JPG?id="+result[1]+"&ext=JPG")```

**Comment by maxaggedon** [comment] 2019-08-07 12:20
I just submitted #76 which addresses the problem of uploading images as JPEG instead of HEIC.
Might be related, I am not sure...

**Comment by tomtargosz** [comment] 2019-08-08 20:27
@maxaggedon I used your fork to see if it fixed this issue, unfortunately not.

**Comment by Abdelrahman-Nabil** [comment] 2019-08-28 23:53
Is this has a fix or still unresolved ? i'm having the same issue

**Comment by jzyds** [comment] 2019-09-08 15:41
https://github.com/jzyds/react-native-convert-ph-asset

**Comment by BSSUTAR** [comment] 2019-09-19 06:35
Any updates on this issue?

**Comment by KA-32** [comment] 2019-09-24 16:51
Hi Guys, I found way to solve this issue in iOS. We can write another method like getSelectedPhoto() and pass the selected image path which is ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001. In RNCCameraRollManager.m we can use **requestContentEditingInputWithOptions** to get the path of selected image. I will raise PR on this

**Comment by shrijan** [comment] 2019-09-25 05:30
`CameraRoll.saveToCameraRoll(photo.uri, 'photo').then(
            u => {
                let name = Date.now();
                let data =  new FormData()
                data.append ('file',{
                    uri : u,
                    type: 'image/jpg',
                    name: name+'.jpg'
                })
                console.log('image upload',data)
                promises.push(axios.post(url,data));
               }
        )

`

Need help with this was working fine. it only works with android. As said above
ph://726E6F49-122A-44E8-84C4-3669CD8FFD59/L0/001

Thanks

**Comment by CesarRivasP** [comment] 2019-09-25 13:57
> Hola chicos, encontré la forma de resolver este problema en iOS. Podemos escribir otro método como getSelectedPhoto () y pasar la ruta de la imagen seleccionada que es ph: // ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED / L0 / 001. En RNCCameraRollManager.m podemos usar **requestContentEditingInputWithOptions** para obtener la ruta de la imagen seleccionada. Levantaré relaciones públicas sobre esto

Can you explain how to carry out that solution?

**Comment by KA-32** [comment] 2019-09-25 18:03
> > Hola chicos, encontré la forma de resolver este problema en iOS. Podemos escribir otro método como getSelectedPhoto () y pasar la ruta de la imagen seleccionada que es ph: // ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED / L0 / 001. En RNCCameraRollManager.m podemos usar **requestContentEditingInputWithOptions** para obtener la ruta de la imagen seleccionada. Levantaré relaciones públicas sobre esto
> 
> Can you explain how to carry out that solution?

@CesarRivasP Could you please check this link ?
https://github.com/KA-32/react-native-cameraroll
I have forked repo and updated with fix. Currently testing and once ready will raise PR. 
If possible could you please help me in testing ?

Thanks

**Comment by shrijan** [comment] 2019-09-25 23:48
> https://github.com/KA-32/react-native-cameraroll

i am getting error
 TypeError: null is not an object (evaluating '_nativeInterface.default.saveToCameraRoll')]

**Comment by KA-32** [comment] 2019-09-26 05:18
> > https://github.com/KA-32/react-native-cameraroll
> 
> i am getting error
> TypeError: null is not an object (evaluating '_nativeInterface.default.saveToCameraRoll')]

CameraRoll.getSelectedPhoto(`ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001 `)
     .then(r => {
       //Use this filepath to upload image to server.
       console.log(r.node.image.filepath);
     })
     .catch((err) => {
        //No selected image found
     });

Is this method giving error?

Could you please help in reproducing the issue ?

Thanks

**Comment by shrijan** [comment] 2019-09-26 23:32
` onPictureSaved = async photo => {
        
        CameraRoll.saveToCameraRoll(photo.uri, 'photo').then(
            u => {
            //u is ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001
                CameraRoll.getSelectedPhoto(u)
                .then(r => {
                    //Use this filepath to upload image to server.
                    console.log('Use this filepath to upload image to server',r.node.image.filepath);
                })
                .catch((err) => {
                    //No selected image found
                });
                
                
                }
              
               
            }
        )
    }`

i am getting error with above code
TypeError: null is not an object (evaluating '_nativeInterface.default.saveToCameraRoll')]

**Comment by CesarRivasP** [comment] 2019-09-27 13:51
For my part, I solved my problem. This was that the uri was not valid when converting images to base64. I solved it as follows:

```
let imagePATH = null;
if(Platform.OS === 'ios'){
let regex = /://(.{36})//i;
let result = uriPhoto.match(regex);
let photoPATH = assets-library://asset/asset.JPG?id=${result[1]}&ext=JPG;

  const dest = `${RNFS.TemporaryDirectoryPath}${Math.random().toString(36).substring(7)}.jpg`;

  imagePATH = await RNFS.copyAssetsFileIOS(photoPATH, dest, 500, 500, 1.0, 1.0, 'contain');
}
else if(Platform.OS === 'android'){
  imagePATH = photo;
}

const photoBase64 = await RNFS.readFile(imagePATH, 'base64');
```

**Comment by shrijan** [comment] 2019-10-01 00:41
Any idea about issue

**Comment by mihaislobozeanu** [comment] 2019-11-04 19:09
Hi to all,
After analysing the iOS code I've found that it is fetching the asset for upload, but only if the uri starts with ph-upload, for images and also for videos. So, before upload 
`
if (asset.uri.startsWith('ph://')) {
   asset.uri = 'ph-upload' + asset.uri.substring(2);
}
` should upload the original asset, not the thumbnail. You don't need KA-32 solution, nor react-native-convert-ph-asset package.

**Comment by Dellybro** [comment] 2019-11-05 19:15
> For my part, I solved my problem. This was that the uri was not valid when converting images to base64. I solved it as follows:
> 
> ```
> let imagePATH = null;
> if(Platform.OS === 'ios'){
> let regex = /://(.{36})//i;
> let result = uriPhoto.match(regex);
> let photoPATH = assets-library://asset/asset.JPG?id=${result[1]}&ext=JPG;
> 
>   const dest = `${RNFS.TemporaryDirectoryPath}${Math.random().toString(36).substring(7)}.jpg`;
> 
>   imagePATH = await RNFS.copyAssetsFileIOS(photoPATH, dest, 500, 500, 1.0, 1.0, 'contain');
> }
> else if(Platform.OS === 'android'){
>   imagePATH = photo;
> }
> 
> const photoBase64 = await RNFS.readFile(imagePATH, 'base64');
> ```

This works. just don't forget to delete this photos afterwards.

**Comment by bartolkaruza** [comment] 2019-11-07 13:55
There seem to be good workarounds for this issue. I'm closing this, for now, just let me know if anyone wants to provide a PR that makes the above easier for everyone and I'll re-open.

**Closed by bartolkaruza** 2019-11-07 13:55 UTC

**Comment by piyushamola** [comment] 2019-12-11 17:09
I have solved this using the expo-media-library 
https://docs.expo.io/versions/latest/sdk/media-library/### 

async myFunc() {
let uri = "ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001"
let myAssetId = uri.slice(5);
let returnedAssetInfo = await MediaLibrary.getAssetInfoAsync(myAssetId);
console.log(returnedAssetInfo.localUri);   
}

**Comment by tudiantuan** [comment] 2020-03-24 09:54
> Hi to all,
> After analysing the iOS code I've found that it is fetching the asset for upload, but only if the uri starts with ph-upload, for images and also for videos. So, before upload
> `if (asset.uri.startsWith('ph://')) { asset.uri = 'ph-upload' + asset.uri.substring(2); }` should upload the original asset, not the thumbnail. You don't need KA-32 solution, nor react-native-convert-ph-asset package.

I get error Error: ENOENT: no such file or directory, open 'ph-upload://5A73648C-7869-4C77-B3C3-DF437B4F87BA/L0/001'  when use RNFS.readFile(imagePATH, 'base64')

**Comment by chai86** [comment] 2020-03-27 13:58
This worked for me [](https://github.com/ivpusic/react-native-image-crop-picker/issues/384#issuecomment-317628146)

**Comment by yvbeek** [comment] 2020-04-02 14:00
This is still kinda difficult on iOS. Getting a photo or video from the user's library, so that you can upload it to a server is a common use case. 

How can we make this easier?

**Comment by mihaislobozeanu** [comment] 2020-06-03 06:05
> > Hi to all,
> > After analysing the iOS code I've found that it is fetching the asset for upload, but only if the uri starts with ph-upload, for images and also for videos. So, before upload
> > `if (asset.uri.startsWith('ph://')) { asset.uri = 'ph-upload' + asset.uri.substring(2); }` should upload the original asset, not the thumbnail. You don't need KA-32 solution, nor react-native-convert-ph-asset package.
> 
> I get error Error: ENOENT: no such file or directory, open 'ph-upload://5A73648C-7869-4C77-B3C3-DF437B4F87BA/L0/001' when use RNFS.readFile(imagePATH, 'base64')

Hi,
The workaround was just for uploading the image with fetch, not for using it with RNFS or other library.

**Comment by killderycoelho** [comment] 2020-07-13 19:00
This work from me!!!

`if (this.state.photo) {
                bodyData.push({
                    name: 'photo',
                    filename: this.state.photo.fileName,
                    type: this.state.photo.type,
                    data: Platform.OS === "android" ? RNFetchBlob.wrap(this.state.photo.uri) : RNFetchBlob.wrap(this.state.photo.origURL),
                    uri: Platform.OS === "android" ? this.state.photo.uri : this.state.photo.origURL
                });
            }`

**Comment by marlti7** [comment] 2020-08-05 09:57
why close this

**Comment by PatelRahil** [comment] 2020-09-01 18:40
I had used the string manipulation method of converting a `ph://` filepath to and `asset-library` filepath, but now I'm getting the error:
`NativeFirebaseError: [storage/asset-library-removed] iOS 'asset-library://' & 'ph://' URLs have been removed, please provide the correct path to resource.` after updating all of my @react-native-firebase packages. What's the format for the "correct path to resource" supposed to be now?

**Comment by efstathiosntonas** [comment] 2020-12-03 15:45
One workaround is to use `@react-native-community/image-editor`

```
const uri = await ImageEditor.cropImage(selectedPhoto.node.image.uri, {
      size: {
        width: selectedPhoto.node.image.width,
        height: selectedPhoto.node.image.height
      },
      offset: {
        x: 0,
        y: 0
      }
    });
```

will return image path from: 
```
{"group_name": "All Photos", "image": {"fileSize": null, "filename": "d1c966d5-48cb-461c-8658-f4121d16a032.jpg", "height": null, "playableDuration": null, "uri": "ph://ADAF64C0-65BB-48F1-96BB-4ABE1A7EAD08/L0/001", "width": null}, "location": null, "timestamp": 1606919787, "type": "image"}
```

to:
```
"file:///var/mobile/Containers/Data/Application/911A0465-F647-4D87-8394-A323DDF9C456/Library/Caches/ReactNative_cropped_image_/03A48EF3-0C12-4F8C-B5B1-5DE424B40FB4.jpg"
```

**Comment by krupalikevadiya** [comment] 2021-02-09 13:00
Same issue did you have any working solution for it?

**Comment by MarcoScabbiolo** [comment] 2021-02-09 13:52
First convert the `ph://` uri to an asset uri:

```javascript
if (uri.includes('ph://')) {
  let id = uri.replace('ph://', '')
  id = id.substring(0, id.indexOf('/'))
  uri = `assets-library://asset/asset.${ext}?id=${id}&ext=${ext}`
  console.log(`Converted file uri to ${uri}`)
}
```

Then copy the asset file to a temp location to use it, [react-native-fs](https://github.com/itinance/react-native-fs) has very useful helpers for this.

```javascript
const encodedUri = encodeURI(uri)
const destPath = `${RNFS.TemporaryDirectoryPath}temp.${ext}`

if (isVideo) {
  uri = await RNFS.copyAssetsVideoIOS(encodedUri, destPath)
} else {
  uri = res = await RNFS.copyAssetsFileIOS(encodedUri, destPath, 0, 0)
}

**Comment by krupalikevadiya** [comment] 2021-02-12 05:54
@MarcoScabbiolo it's worked for me..thank you

**Comment by efstathiosntonas** [comment] 2021-02-12 06:18
For everyone’s info, there’s a new module for  files handling https://github.com/alpha0010/react-native-file-access but it doesn’t support buffer yet.

**Comment by ozdemircibaris** [comment] 2021-05-18 13:07
`let localUri = photoGalleryItem.uri;`
`let filename = Platform.OS == 'android' ? localUri.split('/').pop():localUri.split('/')[2];`
`let type = photoGalleryItem.type.includes('image') ? `image/jpeg` : `video/mp4`;`
`formData.append('media_url', { uri: localUri, type: type, name: filename })`

**Comment by ajayAloha** [comment] 2021-11-18 15:08
> First convert the `ph://` uri to an asset uri:
> 
> ```js
> if (uri.includes('ph://')) {
>   let id = uri.replace('ph://', '')
>   id = id.substring(0, id.indexOf('/'))
>   uri = `assets-library://asset/asset.${ext}?id=${id}&ext=${ext}`
>   console.log(`Converted file uri to ${uri}`)
> }
> ```
> 
> Then copy the asset file to a temp location to use it, [react-native-fs](https://github.com/itinance/react-native-fs) has very useful helpers for this.
> 
> ```js
> const encodedUri = encodeURI(uri)
> const destPath = `${RNFS.TemporaryDirectoryPath}temp.${ext}`
> 
> if (isVideo) {
>   uri = await RNFS.copyAssetsVideoIOS(encodedUri, destPath)
> } else {
>   uri = await RNFS.copyAssetsFileIOS(encodedUri, destPath, 0, 0)
> }
> ```

Hi @MarcoScabbiolo, Thanks for the workaround but I had more success with  `DocumentDirectoryPath`. Below is the code function which I have created for the same :)

`const RNFS = require('react-native-fs');

// create a path you want to write to
// :warning: on iOS, you cannot write into `RNFS.MainBundlePath`,
// but `RNFS.DocumentDirectoryPath` exists on both platforms and is writable
const path = RNFS.DocumentDirectoryPath + '/';

// Copies a video from assets-library, that is prefixed with 'assets-library://asset/asset.MOV?...' to a specific destination
const copyVideoAssetIOS = async (filePath) => {
  try {
    const fileNameLength = filePath.length;
    const ext = filePath.substring(fileNameLength - 3);
    const encodedUri = encodeURI(filePath);
    const destPath = `${path}${Date.now()}.${ext}`;
    const uri = await RNFS.copyAssetsVideoIOS(encodedUri, destPath);
    return uri;
  } catch (err) {
    console.log(
      '🚀 -> file: File.js -> line 42 -> copyVideoAssetIOS -> err',
      err,
    );
    return false;
  }
};`

**Comment by JohnBerd** [comment] 2021-12-23 18:13
GiFs images are converted into JPEGs while copied to the temporarily folder, any workaround for this?

**Comment by formula1** [comment] 2022-01-25 21:19
> This worked for me (credit to @gameboyVito):
> 
> ```
> /**
>  * I write a litte util method to convert localIdentifier to assetURL in JavaScript
>  * @param localIdentifier looks like 91B1C271-C617-49CE-A074-E391BA7F843F/L0/001
>  * @param ext the extension: JPG, PNG, MOV
>  * @returns {string}
>  */
> export const convertLocalIdentifierToAssetLibrary = (localIdentifier, ext) => {
>     const hash =  localIdentifier.split('/')[0];
>     return `assets-library://asset/asset.${ext}?id=${hash}&ext=${ext}`;
> };
> ```
> 
> to output: `"assets-library://asset/asset.MP4?id=60F75F00-0307-645E-875D-B0927CE2BB7D&ext=MP4".`

This almost worked for me except i had to use `localIdentifier.split('/')[2]` instead

**Comment by docongminh1** [comment] 2022-09-23 05:43
> First convert the `ph://` uri to an asset uri:
> 
> ```js
> if (uri.includes('ph://')) {
>   let id = uri.replace('ph://', '')
>   id = id.substring(0, id.indexOf('/'))
>   uri = `assets-library://asset/asset.${ext}?id=${id}&ext=${ext}`
>   console.log(`Converted file uri to ${uri}`)
> }
> ```
> 
> Then copy the asset file to a temp location to use it, [react-native-fs](https://github.com/itinance/react-native-fs) has very useful helpers for this.
> 
> ```js
> const encodedUri = encodeURI(uri)
> const destPath = `${RNFS.TemporaryDirectoryPath}temp.${ext}`
> 
> if (isVideo) {
>   uri = await RNFS.copyAssetsVideoIOS(encodedUri, destPath)
> } else {
>   uri = await RNFS.copyAssetsFileIOS(encodedUri, destPath, 0, 0)
> }
> ```

this work for me, you save my day
