### ISSUE TITLE
Error Domain=PHPhotosErrorDomain Code=-1 "(null)"

### ISSUE THREAD

**Issue by billxie1988** [react-native-community/react-native-cameraroll#159] opened 2020-03-27 03:47 UTC
- the code below will cause error on iOS 13 devices when import uri is https://xxxxx.png

```assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImageAtFileURL:inputURI];```

- this way works well

```
NSData *data = [NSData dataWithContentsOfURL:inputURI];
UIImage *image = [UIImage imageWithData:data];
assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImage:image];
```

**Comment by bartolkaruza** [comment] 2020-05-07 18:53
Thank you for posting the working code! Closing this as duplicate of #157

**Closed by bartolkaruza** 2020-05-07 18:53 UTC
