### ISSUE TITLE
[IOS] Video display crashes on display with it's thumbnail url

### ISSUE THREAD

**Issue by talal7860** [react-native-community/react-native-cameraroll#70] opened 2019-07-25 16:35 UTC
# Bug
I'm displaying a list of photos and videos from the library on IOS, it works fine when fetching only photos, but when I fetch videos, it obviously returns the thumbnail of the video, trying to display it crashes the app. The same code works on importing `CameraRoll` directly from `react-native` core libraries.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 604.50 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.10.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
```

Library version: 1.1.1

## Steps To Reproduce

1. `react-native init myApp`
2. install this library.
3. Include it in the pod file and run `pod install` in the `ios` folder.

And calling the `Attachments` in the render function of the parent class with the photos passed as props.
...

Describe what you expected to happen:

1. Display the thumbnails of the video as other photos.

## Reproducible sample code

```
const Attachments = ({ photos }) => {
const [ index, setIndex ] = useState(null);
return (<ScrollView>
              {
                      photos.map((p, i) => {
                        return (
                        <TouchableHighlight
                          style={{ opacity: i === index ? 0.5 : 1 }}
                          key={i}
                          underlayColor="transparent"
                          onPress={() => setIndex(i)}
                        >
                          <Image
                            style={styles.image}
                            source={{ uri: p.node.image.uri }}
                          />
                        </TouchableHighlight>
                      ));
                      }
                  }
            </ScrollView>
);
};
```

Use `getPhotos` to get photos
```
CameraRoll.getPhotos(params)
        .then((r) => {
          this.setState({ photos: r.edges });
        })
        .catch((err) => {
          if (err.message === 'User denied access') {
            showAlert(i18n.t('camera.permission_denied'), i18n.t('camera.permission_denied_message'), null);
          } else {
            showAlert(i18n.t('camera.error'), i18n.t('camera.error_loading_photos'), null);
          }
        });
```

**Comment by jzyds** [comment] 2019-09-08 15:47
https://github.com/jzyds/react-native-convert-ph-asset

**Comment by meiqi1992** [comment] 2019-10-09 08:30
@talal7860 same issue. you resolved it?

**Comment by Brouilles** [comment] 2019-10-22 10:55
Same here.

**Comment by bartolkaruza** [comment] 2019-11-07 14:50
This is a duplicate of https://github.com/react-native-community/react-native-cameraroll/issues/52 and the issue is related to `ph://` uri's. There are workarounds posted at that other issue as well as using the react-native-convert-ph-asset library posted above by @jzyds . Closing for now.

**Closed by bartolkaruza** 2019-11-07 14:50 UTC
