### ISSUE TITLE
Android SDK 29 Breaks GetPhotos()

### ISSUE THREAD

**Issue by aarongrider** [react-native-community/react-native-cameraroll#88] opened 2019-09-26 00:50 UTC
# Bug

When changing the targetSdkVersion from 28 to 29, in build.gradle, CameraRoll.getPhotos() fails with an error "Invalid column longitude".

![image](https://user-images.githubusercontent.com/5132904/65649603-18892e80-dfbc-11e9-8dcf-148b3e4fd9c1.png)

I have tried with both a wrapper app and the Example app included in this library. It looks like the native module needs to be updated to support this SDK version.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 683.00 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 25.0.0, 27.0.3, 28.0.2, 28.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.0 => 0.61.0
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 1.2.1

## Steps To Reproduce

1. Update targetSdkVersion in Example/build.gradle to 29
2. Attempt to run example
...

Describe what you expected to happen:

1. Example runs as expected

**Comment by aarongrider** [comment] 2019-09-26 17:01
This issue is due to this constant being depreciated
https://developer.android.com/reference/android/provider/MediaStore.Images.ImageColumns#LATITUDE

**Comment by aarongrider** [comment] 2019-10-01 03:38
There are a few possible solutions to this issue, one of them being removing location data from the query and therefore module. I am happy to submit a PR to the project with these changes if needed.

**Comment by Gjoshi3107** [comment] 2019-10-17 04:58
Not just [Latitude](https://developer.android.com/reference/android/provider/MediaStore.Images.ImageColumns#LATITUDE) and [Longitude](https://developer.android.com/reference/android/provider/MediaStore.Images.ImageColumns#LONGITUDE) but [MediaStore.MediaColumns.DATA](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns.html#DATA) is also deprecated in API level 29 resulting in error occurring when root sdk version is 29. 
Is it all right to delete the DATA data as well???

**Comment by Gjoshi3107** [comment] 2019-10-17 05:25
it seems decreasing the sdk version to 28 works for now

**Comment by Gjoshi3107** [comment] 2019-10-17 06:07
Not just [Latitude](https://developer.android.com/reference/android/provider/MediaStore.Images.ImageColumns#LATITUDE) and [Longitude](https://developer.android.com/reference/android/provider/MediaStore.Images.ImageColumns#LONGITUDE) but [MediaStore.MediaColumns.DATA](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns.html#DATA) is also deprecated in API level 29 resulting in error.
Is it all right to delete the DATA data as well???

Update:-
it seems decreasing the sdk version to 28 works for now

faced this issue at:-
com.reactnativecommunity.cameraroll.CameraRollModule$GetMediaTask.doInBackgroundGuarded
Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()
Caused by java.lang.IllegalArgumentException
Invalid column longitude
Android Os:- Android 10
Devices Affected:-
- Google Pixel XL
- Google Pixel 3a 
- Asus ZenFone Max Pro M1 (ZB602KL) (WW) / Max Pro M1 (ZB601KL) (IN)

**Comment by bartolkaruza** [comment] 2019-11-07 13:47
closing as duplicate of https://github.com/react-native-community/react-native-cameraroll/issues/93

**Closed by bartolkaruza** 2019-11-07 13:47 UTC

**Comment by PaperbagWriter** [comment] 2020-03-03 14:14
> There are a few possible solutions to this issue, one of them being removing location data from the query and therefore module. I am happy to submit a PR to the project with these changes if needed.

Opted for a temporary solution (removing longitude-latitude information)
I'd love that PR if you still have those ideas, or if you've made those changes in your project 😄
