### ISSUE TITLE
[IOS] CameraRoll.save save duplicated images

### ISSUE THREAD

**Issue by HauLuu** [react-native-community/react-native-cameraroll#190] opened 2020-06-01 02:59 UTC
# Summary
CameraRoll.save save duplicated images on IOS but not Android.

## Environment info
  - Binaries:
    Node: 13.12.0 
    Yarn: 1.22.4 
    npm: 6.14.4 
    Watchman: 4.9.0 
  - npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0
  - IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild

Library version: 1.7.2

## Reproducible sample code
The image was taken by react-native-camera.

if (RNFS.exists(`${RNFetchBlob.fs.dirs.PictureDir}/MyProjectName`)) {
      CameraRoll.save(this.state.uri, {
        type: 'photo',
        album: `${RNFetchBlob.fs.dirs.PictureDir}/MyProjectName`,
      })
    } else {
      RNFetchBlob.fs.mkdir(`${RNFetchBlob.fs.dirs.PictureDir}/MyProjectName`)
        .then((result) => {
          CameraRoll.save(this.state.uri, {
            type: 'photo',
            album: `${RNFetchBlob.fs.dirs.PictureDir}/MyProjectName`,
          })
        })
        .catch((error) => {
          console.log(error);
        })
    }

After this code, I found the taken image was duplicated in the Photo app.

**Comment by bartolkaruza** [comment] 2020-06-01 09:06
Probably a duplicate of #75 . Let's try and work through a fix for #41 first and see if all of these other issues are side-effects of the same problem.

**Comment by HauLuu** [comment] 2020-06-01 12:31
Actually. I didn't use getPhoto method. I took a picture using react-native-camera. Then saved it using snippet above.

After that I opened the Photo App and saw the taken image was duplicated.

**Comment by bartolkaruza** [comment] 2020-06-08 09:28
Can you check that the picture is not there in the Photo App, before calling `Cameraroll.save`?

**Comment by HauLuu** [comment] 2020-06-10 00:38
I'm so sorry for wasting your time. The root cause comes from my side. My app requires opening another application after taking a picture. That process somehow creates a duplicated image. There is nothing to do with react-native-cameraroll. 

Truly sorry for wasting your time. :(

**Closed** 2020-06-10 00:38 UTC
Labels: bug

**Comment by bartolkaruza** [comment] 2020-06-16 09:08
@HauLuu No worries! Thanks for taking the time to open an issue, it helps us improve the library.
